//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Pinz.Client.DomainModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Pinz.Client.DomainModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name required.
        /// </summary>
        internal static string Category_Name_Required {
            get {
                return ResourceManager.GetString("Category_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project required.
        /// </summary>
        internal static string Category_Project_Required {
            get {
                return ResourceManager.GetString("Category_Project_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company must be set.
        /// </summary>
        internal static string Company_Name_Required {
            get {
                return ResourceManager.GetString("Company_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company required.
        /// </summary>
        internal static string Project_Company_Required {
            get {
                return ResourceManager.GetString("Project_Company_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name required.
        /// </summary>
        internal static string Project_Name_Required {
            get {
                return ResourceManager.GetString("Project_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category must be set.
        /// </summary>
        internal static string Task_Category_Required {
            get {
                return ResourceManager.GetString("Task_Category_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation time required.
        /// </summary>
        internal static string Task_CreationTime_Required {
            get {
                return ResourceManager.GetString("Task_CreationTime_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaskName required.
        /// </summary>
        internal static string Task_TaskName_Required {
            get {
                return ResourceManager.GetString("Task_TaskName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status required.
        /// </summary>
        internal static string Task_TaskStatus_Required {
            get {
                return ResourceManager.GetString("Task_TaskStatus_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        internal static string TaskService_NewCategoryName {
            get {
                return ResourceManager.GetString("TaskService_NewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task.
        /// </summary>
        internal static string TaskService_NewTaskName {
            get {
                return ResourceManager.GetString("TaskService_NewTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company must be set.
        /// </summary>
        internal static string User_Company_Required {
            get {
                return ResourceManager.GetString("User_Company_Required", resourceCulture);
            }
        }
    }
}
